//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceNow_XMLGenerator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XMLStaticValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XMLStaticValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InsuranceNow_XMLGenerator.Resources.XMLStaticValues", typeof(XMLStaticValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAIC.
        /// </summary>
        internal static string DTOApplication_DTOBasicPolicy_CarrierCd {
            get {
                return ResourceManager.GetString("DTOApplication_DTOBasicPolicy_CarrierCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAIC.
        /// </summary>
        internal static string DTOApplication_DTOBasicPolicy_CarrierGroupCd {
            get {
                return ResourceManager.GetString("DTOApplication_DTOBasicPolicy_CarrierGroupCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA.
        /// </summary>
        internal static string DTOApplication_DTOBasicPolicy_ControllingStateCd {
            get {
                return ResourceManager.GetString("DTOApplication_DTOBasicPolicy_ControllingStateCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Auto.
        /// </summary>
        internal static string DTOApplication_DTOBasicPolicy_Description {
            get {
                return ResourceManager.GetString("DTOApplication_DTOBasicPolicy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted Renewal.
        /// </summary>
        internal static string DTOApplication_DTOBasicPolicy_PolicyNumber {
            get {
                return ResourceManager.GetString("DTOApplication_DTOBasicPolicy_PolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waic-CA-PersonalAuto-v01-00-01.
        /// </summary>
        internal static string DTOApplication_DTOBasicPolicy_ProductVersionIdRef {
            get {
                return ResourceManager.GetString("DTOApplication_DTOBasicPolicy_ProductVersionIdRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string DTOApplication_DTOBasicPolicy_RenewedFromPolicyNumber {
            get {
                return ResourceManager.GetString("DTOApplication_DTOBasicPolicy_RenewedFromPolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted Renewal.
        /// </summary>
        internal static string DTOApplication_DTOBasicPolicy_Source {
            get {
                return ResourceManager.GetString("DTOApplication_DTOBasicPolicy_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string DTOApplication_DTOBasicPolicy_SubTypeCd {
            get {
                return ResourceManager.GetString("DTOApplication_DTOBasicPolicy_SubTypeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Start.
        /// </summary>
        internal static string DTOApplication_DTOBasicPolicy_TransactionCd {
            get {
                return ResourceManager.GetString("DTOApplication_DTOBasicPolicy_TransactionCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DTOApplication_DTOBasicPolicy_TreatAsConvRenewal {
            get {
                return ResourceManager.GetString("DTOApplication_DTOBasicPolicy_TreatAsConvRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        internal static string DTOApplication_DTOInsured_EntityTypeCd {
            get {
                return ResourceManager.GetString("DTOApplication_DTOInsured_EntityTypeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        internal static string DTOApplication_DTOInsured_PreferredDeliveryMethod {
            get {
                return ResourceManager.GetString("DTOApplication_DTOInsured_PreferredDeliveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonalAuto.
        /// </summary>
        internal static string DTOApplication_DTOLine_LineCd {
            get {
                return ResourceManager.GetString("DTOApplication_DTOLine_LineCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string DTOApplication_DTOLine_PolicyType {
            get {
                return ResourceManager.GetString("DTOApplication_DTOLine_PolicyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManualRate.
        /// </summary>
        internal static string DTOApplication_DTOLine_RatingService {
            get {
                return ResourceManager.GetString("DTOApplication_DTOLine_RatingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string DTOApplication_DTOLine_StatusCd {
            get {
                return ResourceManager.GetString("DTOApplication_DTOLine_StatusCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string DTOApplication_DTOTransactionInfo_ChargeEndorsementFeeInd {
            get {
                return ResourceManager.GetString("DTOApplication_DTOTransactionInfo_ChargeEndorsementFeeInd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waic-CA-PersonalAuto-v01-00-01.
        /// </summary>
        internal static string DTOApplication_DTOTransactionInfo_RewriteToProductVersion {
            get {
                return ResourceManager.GetString("DTOApplication_DTOTransactionInfo_RewriteToProductVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovation.
        /// </summary>
        internal static string DTOApplication_DTOTransactionInfo_SourceCd {
            get {
                return ResourceManager.GetString("DTOApplication_DTOTransactionInfo_SourceCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Start.
        /// </summary>
        internal static string DTOApplication_DTOTransactionInfo_TransactionCd {
            get {
                return ResourceManager.GetString("DTOApplication_DTOTransactionInfo_TransactionCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Start.
        /// </summary>
        internal static string DTOApplication_DTOTransactionInfo_TransactionShortDescription {
            get {
                return ResourceManager.GetString("DTOApplication_DTOTransactionInfo_TransactionShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverParty.
        /// </summary>
        internal static string DTOApplication_PartyInfo_PartyTypeCd {
            get {
                return ResourceManager.GetString("DTOApplication_PartyInfo_PartyTypeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string DTOApplication_PartyInfo_Status {
            get {
                return ResourceManager.GetString("DTOApplication_PartyInfo_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWProduct::product-master::waic-CA-PersonalAuto-v01-00-01:://ProductSetup[@id=&apos;ProductSetup&apos;].
        /// </summary>
        internal static string DTOApplication_QuestionReplies_QuestionSourceMDA {
            get {
                return ResourceManager.GetString("DTOApplication_QuestionReplies_QuestionSourceMDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElectronicPaymentSource-77832465-342.
        /// </summary>
        internal static string DTOBasicPolicy_ElectronicPaymentSource_id {
            get {
                return ResourceManager.GetString("DTOBasicPolicy_ElectronicPaymentSource_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string DTOBasicPolicy_ElectronicPaymentSource_MethodCd {
            get {
                return ResourceManager.GetString("DTOBasicPolicy_ElectronicPaymentSource_MethodCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallmentSource.
        /// </summary>
        internal static string DTOBasicPolicy_ElectronicPaymentSource_SourceTypeCd {
            get {
                return ResourceManager.GetString("DTOBasicPolicy_ElectronicPaymentSource_SourceTypeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit1.
        /// </summary>
        internal static string DTOCoverage_DTOLimit_LimitCd {
            get {
                return ResourceManager.GetString("DTOCoverage_DTOLimit_LimitCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string DTOCoverage_DTOLimit_TypeCd {
            get {
                return ResourceManager.GetString("DTOCoverage_DTOLimit_TypeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit1|Limit2.
        /// </summary>
        internal static string DTOCoverage1_DTOLimit_LimitCd {
            get {
                return ResourceManager.GetString("DTOCoverage1_DTOLimit_LimitCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurrence|AccidentAggregate.
        /// </summary>
        internal static string DTOCoverage1_DTOLimit_TypeCd {
            get {
                return ResourceManager.GetString("DTOCoverage1_DTOLimit_TypeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit1.
        /// </summary>
        internal static string DTOCoverage2_DTOLimit_LimitCd {
            get {
                return ResourceManager.GetString("DTOCoverage2_DTOLimit_LimitCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurrence.
        /// </summary>
        internal static string DTOCoverage2_DTOLimit_TypeCd {
            get {
                return ResourceManager.GetString("DTOCoverage2_DTOLimit_TypeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsuredParty.
        /// </summary>
        internal static string DTOInsured_PartyInfo_PartyTypeCd {
            get {
                return ResourceManager.GetString("DTOInsured_PartyInfo_PartyTypeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string DTOLine_DTORisk_RiskAddPolicyVersion {
            get {
                return ResourceManager.GetString("DTOLine_DTORisk_RiskAddPolicyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentTransaction.
        /// </summary>
        internal static string DTOLine_DTORisk_RiskAddTransactionNo {
            get {
                return ResourceManager.GetString("DTOLine_DTORisk_RiskAddTransactionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string DTOLine_DTORisk_Status {
            get {
                return ResourceManager.GetString("DTOLine_DTORisk_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivatePassengerAuto.
        /// </summary>
        internal static string DTOLine_DTORisk_TypeCd {
            get {
                return ResourceManager.GetString("DTOLine_DTORisk_TypeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PD.
        /// </summary>
        internal static string DTORisk_DTOCoverage_CoverageCd {
            get {
                return ResourceManager.GetString("DTORisk_DTOCoverage_CoverageCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodily Injury - Per Person /Per Accident|Property Damage.
        /// </summary>
        internal static string DTORisk_DTOCoverage_Description {
            get {
                return ResourceManager.GetString("DTORisk_DTOCoverage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string DTORisk_DTOCoverage_Status {
            get {
                return ResourceManager.GetString("DTORisk_DTOCoverage_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string DTORisk_DTOVehicle_DamageInd {
            get {
                return ResourceManager.GetString("DTORisk_DTOVehicle_DamageInd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string DTORisk_DTOVehicle_RegisterdOwner {
            get {
                return ResourceManager.GetString("DTORisk_DTOVehicle_RegisterdOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string DTORisk_DTOVehicle_Status {
            get {
                return ResourceManager.GetString("DTORisk_DTOVehicle_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DTORisk_DTOVehicle_ValidVinInd {
            get {
                return ResourceManager.GetString("DTORisk_DTOVehicle_ValidVinInd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        internal static string DTORisk_DTOVehicle_VehUseCd {
            get {
                return ResourceManager.GetString("DTORisk_DTOVehicle_VehUseCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BI.
        /// </summary>
        internal static string DTORisk1_DTOCoverage1_CoverageCd {
            get {
                return ResourceManager.GetString("DTORisk1_DTOCoverage1_CoverageCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodily Injury - Per Person /Per Accident.
        /// </summary>
        internal static string DTORisk1_DTOCoverage1_Description {
            get {
                return ResourceManager.GetString("DTORisk1_DTOCoverage1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string DTORisk1_DTOCoverage1_Status {
            get {
                return ResourceManager.GetString("DTORisk1_DTOCoverage1_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PD.
        /// </summary>
        internal static string DTORisk2_DTOCoverage2_CoverageCd {
            get {
                return ResourceManager.GetString("DTORisk2_DTOCoverage2_CoverageCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Damage.
        /// </summary>
        internal static string DTORisk2_DTOCoverage2_Description {
            get {
                return ResourceManager.GetString("DTORisk2_DTOCoverage2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string DTORisk2_DTOCoverage2_Status {
            get {
                return ResourceManager.GetString("DTORisk2_DTOCoverage2_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Application.
        /// </summary>
        internal static string DTORoot_DTOApplication_Description {
            get {
                return ResourceManager.GetString("DTORoot_DTOApplication_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DTORoot_DTOApplication_ReadyToRateInd {
            get {
                return ResourceManager.GetString("DTORoot_DTOApplication_ReadyToRateInd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Process.
        /// </summary>
        internal static string DTORoot_DTOApplication_Status {
            get {
                return ResourceManager.GetString("DTORoot_DTOApplication_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string DTORoot_DTOApplication_TypeCd {
            get {
                return ResourceManager.GetString("DTORoot_DTOApplication_TypeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.10.
        /// </summary>
        internal static string DTORoot_DTOApplication_Version {
            get {
                return ResourceManager.GetString("DTORoot_DTOApplication_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsuredMailingAddr|InsuredGaragingAddr.
        /// </summary>
        internal static string PartyInfo_Addr_AddrTypeCd {
            get {
                return ResourceManager.GetString("PartyInfo_Addr_AddrTypeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactDriver.
        /// </summary>
        internal static string PartyInfo_DriverInfo_DriverInfoCd {
            get {
                return ResourceManager.GetString("PartyInfo_DriverInfo_DriverInfoCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string PartyInfo_DriverInfo_LicenseStatus {
            get {
                return ResourceManager.GetString("PartyInfo_DriverInfo_LicenseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US License.
        /// </summary>
        internal static string PartyInfo_DriverInfo_LicenseType {
            get {
                return ResourceManager.GetString("PartyInfo_DriverInfo_LicenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured does not wish to provide information.
        /// </summary>
        internal static string PartyInfo_DriverInfo_Race {
            get {
                return ResourceManager.GetString("PartyInfo_DriverInfo_Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactName|InsuredName.
        /// </summary>
        internal static string PartyInfo_NameInfo_NameTypeCd {
            get {
                return ResourceManager.GetString("PartyInfo_NameInfo_NameTypeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactPersonal|InsuredPersonal.
        /// </summary>
        internal static string PartyInfo_PersonInfo_PersonTypeCd {
            get {
                return ResourceManager.GetString("PartyInfo_PersonInfo_PersonTypeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string PartyInfo_PhoneInfo_PhoneName {
            get {
                return ResourceManager.GetString("PartyInfo_PhoneInfo_PhoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsuredPhonePrimary.
        /// </summary>
        internal static string PartyInfo_PhoneInfo_PhoneTypeCd {
            get {
                return ResourceManager.GetString("PartyInfo_PhoneInfo_PhoneTypeCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWQuestionFraud|UWQuestionVehicleSharing|UWPublicDelivery|WQuestionOtherDelivery|UWQuestionGaragingLocation|WQuestionOtherVehicles|UWQuestionHousehold.
        /// </summary>
        internal static string QuestionReplies_QuestionReply_Name {
            get {
                return ResourceManager.GetString("QuestionReplies_QuestionReply_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string QuestionReplies_QuestionReply_Value {
            get {
                return ResourceManager.GetString("QuestionReplies_QuestionReply_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string QuestionReplies_QuestionReply_VisibleInd {
            get {
                return ResourceManager.GetString("QuestionReplies_QuestionReply_VisibleInd", resourceCulture);
            }
        }
    }
}
