//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configurations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExcelConfiguration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelConfiguration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Configurations.ExcelConfiguration", typeof(ExcelConfiguration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string AutoGeneral_biCover {
            get {
                return ResourceManager.GetString("AutoGeneral_biCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string AutoGeneral_limMex {
            get {
                return ResourceManager.GetString("AutoGeneral_limMex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string AutoGeneral_medCover {
            get {
                return ResourceManager.GetString("AutoGeneral_medCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        public static string AutoGeneral_pdCover {
            get {
                return ResourceManager.GetString("AutoGeneral_pdCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string AutoGeneral_PolicyNumber {
            get {
                return ResourceManager.GetString("AutoGeneral_PolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string AutoGeneral_roadAssis {
            get {
                return ResourceManager.GetString("AutoGeneral_roadAssis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        public static string AutoGeneral_umbi {
            get {
                return ResourceManager.GetString("AutoGeneral_umbi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string AutoGeneral_umpdcdw {
            get {
                return ResourceManager.GetString("AutoGeneral_umpdcdw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto General.
        /// </summary>
        public static string AutoGeneralSheet {
            get {
                return ResourceManager.GetString("AutoGeneralSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        public static string Driver_birthDate {
            get {
                return ResourceManager.GetString("Driver_birthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string Driver_dateFirstLicense {
            get {
                return ResourceManager.GetString("Driver_dateFirstLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string Driver_DriverNumber {
            get {
                return ResourceManager.GetString("Driver_DriverNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string Driver_driverStatus {
            get {
                return ResourceManager.GetString("Driver_driverStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string Driver_FirstName {
            get {
                return ResourceManager.GetString("Driver_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J.
        /// </summary>
        public static string Driver_Gender {
            get {
                return ResourceManager.GetString("Driver_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string Driver_LastName {
            get {
                return ResourceManager.GetString("Driver_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        public static string Driver_licenseNumber {
            get {
                return ResourceManager.GetString("Driver_licenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string Driver_licenseState {
            get {
                return ResourceManager.GetString("Driver_licenseState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        public static string Driver_maritalStatus {
            get {
                return ResourceManager.GetString("Driver_maritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string Driver_matureDriver {
            get {
                return ResourceManager.GetString("Driver_matureDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string Driver_MiddleName {
            get {
                return ResourceManager.GetString("Driver_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string Driver_occupation {
            get {
                return ResourceManager.GetString("Driver_occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string Driver_Policy {
            get {
                return ResourceManager.GetString("Driver_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string Driver_PolicyNumber {
            get {
                return ResourceManager.GetString("Driver_PolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        public static string Driver_relationShip {
            get {
                return ResourceManager.GetString("Driver_relationShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        public static string Driver_sr22 {
            get {
                return ResourceManager.GetString("Driver_sr22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string DriverSheet {
            get {
                return ResourceManager.GetString("DriverSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string Payment_AccountNumber {
            get {
                return ResourceManager.GetString("Payment_AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string Payment_EftType {
            get {
                return ResourceManager.GetString("Payment_EftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string Payment_PolicyNumber {
            get {
                return ResourceManager.GetString("Payment_PolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string Payment_Token {
            get {
                return ResourceManager.GetString("Payment_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPlan.
        /// </summary>
        public static string PaymentSheet {
            get {
                return ResourceManager.GetString("PaymentSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BB.
        /// </summary>
        public static string Policy_BillReminder {
            get {
                return ResourceManager.GetString("Policy_BillReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        public static string Policy_birthDate {
            get {
                return ResourceManager.GetString("Policy_birthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF.
        /// </summary>
        public static string Policy_effectiveDate {
            get {
                return ResourceManager.GetString("Policy_effectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AJ.
        /// </summary>
        public static string Policy_firstName {
            get {
                return ResourceManager.GetString("Policy_firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR.
        /// </summary>
        public static string Policy_garagingAddress {
            get {
                return ResourceManager.GetString("Policy_garagingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AS.
        /// </summary>
        public static string Policy_garagingCity {
            get {
                return ResourceManager.GetString("Policy_garagingCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT.
        /// </summary>
        public static string Policy_garagingState {
            get {
                return ResourceManager.GetString("Policy_garagingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AU.
        /// </summary>
        public static string Policy_garagingZip {
            get {
                return ResourceManager.GetString("Policy_garagingZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AG.
        /// </summary>
        public static string Policy_inceptionDate {
            get {
                return ResourceManager.GetString("Policy_inceptionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL.
        /// </summary>
        public static string Policy_lastName {
            get {
                return ResourceManager.GetString("Policy_lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AN.
        /// </summary>
        public static string Policy_mailingAddress {
            get {
                return ResourceManager.GetString("Policy_mailingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AO.
        /// </summary>
        public static string Policy_mailingCity {
            get {
                return ResourceManager.GetString("Policy_mailingCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP.
        /// </summary>
        public static string Policy_mailingState {
            get {
                return ResourceManager.GetString("Policy_mailingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AQ.
        /// </summary>
        public static string Policy_mailingZip {
            get {
                return ResourceManager.GetString("Policy_mailingZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB.
        /// </summary>
        public static string Policy_PolicyNumber {
            get {
                return ResourceManager.GetString("Policy_PolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AW.
        /// </summary>
        public static string Policy_primaryPhone {
            get {
                return ResourceManager.GetString("Policy_primaryPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD.
        /// </summary>
        public static string Policy_producerCode {
            get {
                return ResourceManager.GetString("Policy_producerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AH.
        /// </summary>
        public static string Policy_term {
            get {
                return ResourceManager.GetString("Policy_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Info.
        /// </summary>
        public static string PolicySheet {
            get {
                return ResourceManager.GetString("PolicySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF.
        /// </summary>
        public static string Vehicle_annualMileage {
            get {
                return ResourceManager.GetString("Vehicle_annualMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string Vehicle_COLLDEDUCT {
            get {
                return ResourceManager.GetString("Vehicle_COLLDEDUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string Vehicle_COMPDEDUCT {
            get {
                return ResourceManager.GetString("Vehicle_COMPDEDUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AE.
        /// </summary>
        public static string Vehicle_currentOdometer {
            get {
                return ResourceManager.GetString("Vehicle_currentOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB.
        /// </summary>
        public static string Vehicle_DR {
            get {
                return ResourceManager.GetString("Vehicle_DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string Vehicle_LESSOR {
            get {
                return ResourceManager.GetString("Vehicle_LESSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string Vehicle_Make {
            get {
                return ResourceManager.GetString("Vehicle_Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.
        /// </summary>
        public static string Vehicle_Model {
            get {
                return ResourceManager.GetString("Vehicle_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        public static string Vehicle_NO {
            get {
                return ResourceManager.GetString("Vehicle_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string Vehicle_Policy {
            get {
                return ResourceManager.GetString("Vehicle_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string Vehicle_PolicyNumber {
            get {
                return ResourceManager.GetString("Vehicle_PolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA.
        /// </summary>
        public static string Vehicle_PUB {
            get {
                return ResourceManager.GetString("Vehicle_PUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC.
        /// </summary>
        public static string Vehicle_Rental {
            get {
                return ResourceManager.GetString("Vehicle_Rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string Vehicle_VIN {
            get {
                return ResourceManager.GetString("Vehicle_VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string VehicleSheet {
            get {
                return ResourceManager.GetString("VehicleSheet", resourceCulture);
            }
        }
    }
}
